# Generated by Django 4.2.5 on 2024-06-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Para",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("sequence", models.IntegerField(default=1)),
                ("content", models.CharField(max_length=50000, null=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "ad_field_image",
                    models.ImageField(default="", upload_to="blog/images"),
                ),
                ("ad_field_product_name", models.CharField(default="", max_length=10)),
                (
                    "ad_field_price",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "ad_field_model",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                ("ad_field_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="chead0",
        ),
        migrations.RemoveField(
            model_name="post",
            name="chead1",
        ),
        migrations.RemoveField(
            model_name="post",
            name="chead2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="cimages0",
        ),
        migrations.RemoveField(
            model_name="post",
            name="cimages1",
        ),
        migrations.RemoveField(
            model_name="post",
            name="cimages2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="head0",
        ),
        migrations.RemoveField(
            model_name="post",
            name="head1",
        ),
        migrations.RemoveField(
            model_name="post",
            name="head2",
        ),
        migrations.RemoveField(
            model_name="post",
            name="isDeleted",
        ),
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="sno",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AddField(
            model_name="post",
            name="add_to_top",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="latest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="Category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogcategory"
            ),
        ),
        migrations.DeleteModel(
            name="Ad",
        ),
        migrations.AddField(
            model_name="para",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
