# Generated by Django 5.0 on 2024-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_para_remove_post_chead0_remove_post_chead1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='content',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
